#!/usr/bin/env bash
# Most of this is from https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu

shopt -s nullglob globstar

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=dmenu-wl
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

if [ ${#password_files[@]} -eq 1 ]; then
    password=${password_files[0]}
else
    password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")
fi

[[ -n $password ]] || exit

echo "$password" 
pass show "$password" 2>/dev/null
